### ISSUE TITLE
Example in documentation should not use TAL

### ISSUE THREAD

**Issue by fulv** [ploneintranet/pat-checklist-picker#1]
The primary audience of patterns are designers, who should not be expected to read anything other than HTML and CSS.  So the example should be pure HTML, without TAL attributes.  This will also aid in creating demos that can be loaded straight from the filesystem, without any Zope server behind.
Also, do not use JavaScript in illustrating the structure of created links.
See other patterns for guidance.

**Comment by tax** [comment]
Thanks for the feedback this is fixed in [this](https://github.com/ploneintranet/pat-checklist-picker/commit/c561d14bc6dc3ecb0a9442d99e26e2b2c1b914b1) commit.
